
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image"; 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kabylospizza",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/KabylosPizzaLogo.png", // Path to your logo
  }
};

import ReduxProvider from "./state";
import { NavBar } from "@/Components/HeaderNav/page";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider> 
          <NavBar/>
          {children}
        </ReduxProvider>
      </body>
    </html>
   
  );
}
